In [59]:
import numpy as np

In [60]:
def randomNumber(start=0, stop=100):
    return int(np.random.random()*(stop-start) + start)

randomNumber(50,100)

52

In [61]:
a = np.random.random(5)
b = [1,2,3,4,5]
print(a)
print(type(a))
print(b)
print(type(b))

for e in a:
    print(e)


[0.17870615 0.01439678 0.49109126 0.2227021  0.60451676]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>
0.17870614637351634
0.014396783866239327
0.4910912567224056
0.22270209984605738
0.604516761472475


In [62]:
a = np.random.random((3,3))
print(a)
print("Dimensions:{} Shape:{}".format(len(a.shape),a.shape))

[[0.01672208 0.80697015 0.28906303]
 [0.60153376 0.62885791 0.77059259]
 [0.90382825 0.84650975 0.83142431]]
Dimensions:2 Shape:(3, 3)


In [63]:
a = np.random.random((3,3))
print(a)
print(a.dtype)

[[0.48925278 0.5609386  0.54289138]
 [0.47686445 0.30824968 0.26546189]
 [0.1527062  0.08612484 0.89395197]]
float64


In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
(np.ones((5,5)) * 100) * np.eye(5)

array([[100.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0., 100.]])

In [80]:
a = np.ones((5,3))
a.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
a = np.eye(5).T
print(a)
print(a.size)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
25


In [91]:
a = [[1,2,3,4,5,6,7,8,8]]
b = np.asarray(a)
print(type(a),type(b))
print(a,b)
print(b.T)

<class 'list'> <class 'numpy.ndarray'>
[[1, 2, 3, 4, 5, 6, 7, 8, 8]] [[1 2 3 4 5 6 7 8 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [8]]


In [99]:
c = np.asarray([1,2,3,4,5,6,7,8])
np.reshape(c,(2,2,2))

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [109]:
c = np.asarray(range(5))
c.dtype
print(c,c.dtype)

[0 1 2 3 4] int64


In [110]:
c = np.asarray(range(5), dtype='float64')
c.dtype
print(c,c.dtype)

[0. 1. 2. 3. 4.] float64


In [132]:
c = np.random.random((5,5))
print(c)

# same
#c[0][0]
#c[0,0]

# same
#c[0]
#c[0,:]

# slicing
#c[1:-1,1:-1]
c[0:2,0:2]

[[0.43275854 0.10804474 0.76285691 0.1149011  0.92557273]
 [0.20170292 0.74178671 0.9093628  0.37878944 0.07057383]
 [0.54524711 0.1074913  0.72152285 0.14296884 0.56127465]
 [0.33911671 0.60347834 0.15405679 0.95591904 0.18284611]
 [0.9963191  0.86676217 0.91838008 0.81834131 0.48626429]]


array([[0.43275854, 0.10804474],
       [0.20170292, 0.74178671]])

In [138]:
c = np.ones((5,3)).T
print(c)
#np.sum(c)
np.sum(c,axis=0)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([3., 3., 3., 3., 3.])

In [142]:
a = np.random.random((3,3,3))
print(a)
c = np.sum(a,axis=0)
print(c)
np.sum(c,axis=1)

[[[0.98622604 0.5460116  0.54285699]
  [0.18253128 0.35141826 0.03520049]
  [0.08165841 0.0237793  0.55890022]]

 [[0.50214395 0.16107948 0.39575185]
  [0.39311661 0.3553764  0.12072209]
  [0.09772078 0.92310778 0.88803524]]

 [[0.48416096 0.13395478 0.52636871]
  [0.00165867 0.61735486 0.03423583]
  [0.69079043 0.42692296 0.89176074]]]
[[1.97253095 0.84104585 1.46497756]
 [0.57730656 1.32414952 0.19015841]
 [0.87016961 1.37381004 2.3386962 ]]


array([4.27855435, 2.09161449, 4.58267585])

In [150]:
a = np.random.random((3,3,3))
print(a.size)
# np.hstack(np.hstack(a))
a.reshape(a.size)

27


array([0.08409478, 0.64449428, 0.32711821, 0.85064104, 0.73877535,
       0.28505798, 0.65671296, 0.72390723, 0.04301731, 0.54261218,
       0.72593597, 0.02011736, 0.21891344, 0.08937921, 0.47399243,
       0.76173493, 0.01839946, 0.89415416, 0.97458821, 0.57464758,
       0.8264994 , 0.10375223, 0.92842117, 0.85836248, 0.87388318,
       0.97113353, 0.95907318])

In [169]:
a = np.random.random((3,4))
print(a)
print(a[1:3,:])
#np.mean(a[:,0:3], axis=1)
np.std(a[:,0:3], axis=1)


[[0.14642938 0.89262862 0.76915216 0.74199982]
 [0.68737641 0.67657905 0.86562075 0.12743942]
 [0.03076997 0.45672648 0.43498284 0.55690397]]
[[0.68737641 0.67657905 0.86562075 0.12743942]
 [0.03076997 0.45672648 0.43498284 0.55690397]]


array([0.32657199, 0.0866823 , 0.19587405])

In [198]:
x = np.arange(5)
print(x, x.shape)
x = np.expand_dims(x, axis=0).T
print(x, x.shape)
y = np.flip(x,axis=0)
print(y)
lst = [x,y,x,y,x]
d = np.concatenate(lst, axis=1)
print(d)
np.mean(d,axis=1)

[0 1 2 3 4] (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)
[[4]
 [3]
 [2]
 [1]
 [0]]
[[0 4 0 4 0]
 [1 3 1 3 1]
 [2 2 2 2 2]
 [3 1 3 1 3]
 [4 0 4 0 4]]


array([1.6, 1.8, 2. , 2.2, 2.4])